name: riverpod_navigator_go_router
description: go_router examples
version: 0.1.0
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
publish_to: 'none'

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hooks_riverpod:  ^2.3.6
  json_annotation: ^4.8.1
  meta: ^1.9.1
  riverpod_navigator: ^1.0.10
  riverpod:  ^2.3.6

dev_dependencies: 
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  functional_widget: ^0.10.1
  json_serializable: ^6.6.2
  mockito: ^5.4.0
  test: ^1.24.2

flutter:
  uses-material-design: true

dependency_overrides:
  riverpod_navigator:
    path: ../../packages/riverpod_navigator
  riverpod_navigator_core:
    path: ../../packages/riverpod_navigator_core
