name: doc
description: Documentation for riverpod navigation
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks:
  flutter_spinkit:
  functional_widget_annotation:
  hooks_riverpod: 2.0.0-dev.6
  json_annotation: 
  path:
  riverpod_navigator: 
    path: ../../packages/riverpod_navigator
  shared_preferences:

dev_dependencies: 
  # analyzer:
  build_runner:
  functional_widget: 
  json_serializable:
  test:

# dependency_overrides:
#   riverpod_navigator: 
#     path: ../../packages/riverpod_navigator

flutter:
  uses-material-design: true

# https://medium.com/p/c55b627da8a6/edit

# dartdoc
# cd doc\api
# dhttpd
# open http://localhost:8080/index.html

# flutter pub run build_runner watch  --delete-conflicting-outputs

# dart pub publish --dry-run
# dart pub publish
# dart pub publish --force 

# flutter build web --web-renderer html -t lib\async.dart