name: doc
description: Documentation for riverpod navigation
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_spinkit: ^5.2.0
  functional_widget_annotation: ^0.10.0
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  path: ^1.8.3
  riverpod_navigator: ^1.0.10
  shared_preferences: ^2.1.1

dev_dependencies: 
  # analyzer:
  build_runner: ^2.4.4
  functional_widget: ^0.10.1
  json_serializable: ^6.6.2
  test: ^1.24.2

dependency_overrides:
  riverpod_navigator: 
    path: ../../packages/riverpod_navigator
  riverpod_navigator_core: 
    path: ../../packages/riverpod_navigator_core

flutter:
  uses-material-design: true

# https://medium.com/p/c55b627da8a6/edit

# dartdoc
# cd doc\api
# dhttpd
# open http://localhost:8080/index.html

# flutter pub run build_runner watch  --delete-conflicting-outputs

# dart pub publish --dry-run
# dart pub publish
# dart pub publish --force 

# flutter build web --web-renderer html -t lib\async.dart