name: riverpod_navigator_core
description: Simple but powerfull Flutter navigation with riverpod and Navigator 2.0.
version: 1.0.3
homepage: https://github.com/PavelPZ/riverpod_navigator
repository: https://github.com/PavelPZ/riverpod_navigator
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  meta: ^1.7.0
  riverpod: 2.0.0-dev.5
  tuple: ^2.0.0

dev_dependencies: 
  test:

flutter:
  uses-material-design: true

# dartdoc
# cd doc\api
# dhttpd
# open http://localhost:8080/index.html

# flutter pub run build_runner watch  --delete-conflicting-outputs

# flutter format .

# dart pub publish --dry-run
# dart pub publish
# dart pub publish --force 
